CREATE TABLE "restaurants" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"owner_id" text NOT NULL,
	"restaurant_name" text NOT NULL,
	"restaurant_type" text NOT NULL,
	"restaurant_address" text NOT NULL,
	"restaurant_logo" text,
	"restaurant_banner" text,
	"establishment_year" integer,
	"seating_capacity" integer DEFAULT 0 NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"postal_code" integer NOT NULL,
	"description" text,
	"phone_number" integer NOT NULL,
	"email" text NOT NULL,
	"website" text,
	"cuisine" text[],
	"rating" integer,
	"rating_count" integer DEFAULT 0 NOT NULL,
	"corporate_identification_number" text,
	"gst_number" text,
	"fssai_license_number" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"request_status" text DEFAULT 'pending' NOT NULL,
	"approved_at" timestamp,
	"rejected_at" timestamp,
	"status" text DEFAULT 'active' NOT NULL,
	CONSTRAINT "restaurants_slug_unique" UNIQUE("slug"),
	CONSTRAINT "restaurants_status_check" CHECK ("restaurants"."status" IN ('active', 'inactive', 'suspended'))
);
--> statement-breakpoint
ALTER TABLE "restaurants" ADD CONSTRAINT "restaurants_owner_id_auth_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."auth_users"("id") ON DELETE cascade ON UPDATE no action;